### ISSUE TITLE
Meeting №1: Discussing new requirements and old functionality

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#1]
First meeting for the last assessment will be focused on collective understanding of the new project and requirements.

A non-exhaustive agenda:
-----------------------------------
1. Discuss precisely which existing functionality should be rewritten and redesigned
    - Point out bugs and flaws in the implementation. The bugs/flaws may be both code related, but also project related (i.e. not holding up to requirements). A helpful list to start is our [initial research of Risky-D's project](https://docs.google.com/document/d/1U-NAUtjHxwYHCw-iNY93gJa0INs7H6N1BfPuqDxbAbM/edit#)
    - Structure the decisions and clearly define tasks that need to be done in order to fix bugs/flaws
    - Allocate preliminary tasks amongst team members
2. Discuss the design of the [new requirements](https://vle.york.ac.uk/bbcswebdav/pid-2736372-dt-content-rid-6832238_2/courses/Y2017-006404/SEPR%202017-18%20Assessment%204_%20Requirements%20Changes.pdf)
    - Polish any ambiguities
    - Focus on simplicity _(jesus christ pls)_

**Time for meeting:** EDIT: time discussion was removed from this thread to remove cluttering and focus on the meeting discussion, which was devising questions for the client.

**Comment by Nicodaw** [comment]
I am free all Saturday and up until 13:30 on Sunday

**Comment by bnp502** [comment]
I don't have anything on this weekend but would prefer afternoons in case of hangover

**Comment by Gorea235** [comment]
Don't mind when, preferably in the afternoons since I can barely wake up at a decent time

**Comment by Nicodaw** [comment]
With all the input 'till now, how do you feel about **Saturday (tomorrow) 15:00** ? Almost all seminar rooms in Piazza are booked, but we have a fully free CS building.

**Comment by Nicodaw** [comment]
**UPDATE**
----
Meeting scheduled for the **26th (Mon) 13:30 in PZA/109**
If changes should occur due to room unavailability, refer to group chat on Messenger.

**Comment by Gorea235** [comment]
# Questions
These are the questions that we are planning to ask the customer.

## Units
1. Are we allowed to include a bonus card system along side the punishment card system

## Punishment Cards
1. Is it necessary for players to retain cards over multiple turns (i.e. a 'hand' system a-la Yu-Gi-Oh)
2. Do players have a choice over how cards are played/resolved?
3. What limits on acquiring do we have? (i.e. is it entirely up to us or is there a specific limit on how to allocate them?)
4. How much of a laugh do we need to cause? Just a giggle or a hearty laughter?

## Other
1. What limits on copyright do we have?

**Comment by Nicodaw** [comment]
Interview comment has been updated with the full Q&A with our client
