### ISSUE TITLE
Alpha testing

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#10]
A crucial bit of acceptance testing that is yet TBD

**Comment by Gorea235** [comment]
Also, we need to bring the unit tests up to scratch, since they don't work atm

**Comment by Nicodaw** [comment]
An important thing is to define a criterion with which we can evaluate the success of our game. Possible evaluation methods:

Questionnaire ?
Measuring time spent playing ?

Note: Richard said that we should be very concise in our questions to get valuable information.

**Comment by Nicodaw** [comment]
It will be a good idea to do a preliminary beta test on the core functionality before adding the card effect system. [Starting off by writing the questionnaire](http://tinyurl.com/y9pkau6j) is a good idea. The goal of these tests is to see if the game is ultimately fun. A good rule of thumb is to keep questions extremely precise, so vagueness like "on a scale from 1 to 5, how enjoyable is the game" is not advised.

**Comment by Gorea235** [comment]
As of now, the game seems to be running how it did before. If we do some preliminary bug testing now to ensure it's mostly playable, I can upload some builds later to allow for alpha testing with people.

**Comment by Nicodaw** [comment]
Script for alpha test 1
---
1. Introduce the players to what they are going to be doing

> You are going to play a turn base strategy game where you are competing for dominance over the University of York's campus.

2. Explain how the game works. Do not showcase via in game presentation, but just verbally. The goal is to give them guidance but allow them to explore the UI by themselves.

> The map is divided in different sectors, which are all neutral at start. When a game is launched, each player will take control of a base that is denoted by a specific colour.
The base will spawn college students on each turn. A student is a cube with a number denoting the student's level. You can move a student by clicking on him and then on the sector you would want that unit to go to. You have a limit of two moves per turn. You can level up a student by moving him on an empty sector that is not controlled by you.
To attack an enemy college student, simply move your student onto the sector where your opponent's student is. The higher your level is compared to your opponent, the higher your chances of winning. You also have attack and defence bonuses that aid you respectively when attacking or receiving an attack. Every base provides 2 bonuses of either attack or defence.
A random sector contains a minigame which upon completion rewards you with additional attack/defence bonuses.
The goal is to eliminate all other players by conquering their bases and destroying their units.

3. **_Don't show this to the players_** measure the time they take to play a game

4. When they finish the game, give them [this questionnaire ](https://docs.google.com/forms/d/e/1FAIpQLSd4DM-evEG860zKgvvLrX9-LIV1XaqDJU0rIByKa-LqYyrrQA/viewform?usp=sf_link)

**Comment by Gorea235** [comment]
Alpha testing was done ages ago
