### ISSUE TITLE
Evaluation and Testing report

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#11]
# Evaluation and Testing report [ET4.pdf](https://docs.google.com/document/d/1bzadqnIY0soyRmlqFpekqXvkFXu4IYPHAts7jbXoloA/edit)

From the brief:
> ... Evaluation refers to how you determined that the product met its brief and testing refers to how you determined that your code was of appropriate quality.

To ensure code is of appropriate quality:
- [x] #9 Update testing plan and Unit tests
- [x] Discuss need of other testing (i.e. continue their 'black box' GUI tests or justify why we won't do them)
- [x] #7 Refactor codebase

To ensure product brief is met:
- [x] #8 Update requirements
- [x] #10 Alpha testing

**Comment by asyncmeonov** [comment]
Testing documentation and report finalised and added to website and submitted in zip
