### ISSUE TITLE
Final Architecture and Traceability report

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#12]
# Final Architecture and Traceability report [AT4.pdf](https://docs.google.com/document/d/1ls-sOk9e0JCD3UGsfoqLczmOGLJHaDy3JdySB4rAaUA/edit)

Justify design changes by mapping to #8 requirements

**Comment by asyncmeonov** [comment]
Arch and Traceability report finalised and added to website and submitted in zip
