### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#13]
# Implementation [Impl4.pdf](https://docs.google.com/document/d/1eCQ5_Ame20w4PtaKB-VWBleAIFFhXumTfmcMd-nL_kY/edit)

GUI and architectural justification about the new requirements

**Comment by Nicodaw** [comment]
Initial draft added. Important thing to note and remember (for myself as well) is that Impl4.pdf is mainly concerned with the implementation of only the new requirements (card system and postgrad) and anything that has been changed because of them. How the _final implementation of our architecture_ looks like should be in AT4.pdf

**Comment by asyncmeonov** [comment]
Implementation report finalised and added to website and submitted in zip
