### ISSUE TITLE
Project Review Report

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#14]
# Project Review report  [Review4.pdf](https://docs.google.com/document/d/1DVMDfuvwk8D_yZEygYBe5p2ufQtS_7tHiDYgTt4vL7k/edit)

1. Discuss our Scrum usage
2. Explain out transition from Trello to GitHub projects
3. Revisit the Risk table

**Comment by Skyteens** [comment]
i have made a draft but it still needs a lot of work on it which i will work on over the week

**Comment by asyncmeonov** [comment]
Project Review report finalised and added to website and submitted in zip
