### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#16]
To say the game is definitely a game, we would need sounds and corresponding sound controls.
Here is a non-exhaustive list of needed sounds. Please expand this list (directly edit this comment) and provide suggestions with links to different sounds for the particular items on this list (probably best done in comment discussion).

**Note:** all _Button click_ sounds refer to interaction with buttons on the Unity UI and might as well be the same sound, but provide in parentheses which buttons are referred to

Main Menu and Menu interaction in general
-
- [x] Button click sound (interacting with all main menu items)
- [x] Main menu music

Main Game
-
- [x] Unit select sound
- [x] Unit Move sound
- [x] Unit Attack (i.e. battle/ conflict) sound
- [x] Background music
- [x] Turn change sound
- [x] Victory sound
- [x] Player eliminated sound
- [x] Card acquire sound
- [x] Card effect sound
    - [x] Beneficial effect (for when targeting friendly entities)
    - [x] Malicious effect (for when targeting enemy entities)
    - [x] Sector effect (for when you put something on a sector)
    - [x] Sacrifice effect (this is a tricky one. I'd say a 'poof'-like sound ? something that implies vanishing?)

Mini Game
-
- [x] Bird flap sound
- [x] Coin gain sound
- [x] Bird hitting ground/pipe sound
- [x] Mini game music

**Comment by Nicodaw** [comment]
The SoundManager prefab should be moved to MainMenu when we have made all the sounds.

**Comment by Gorea235** [comment]
Sounds have all been added and the sound manager has been implemented fully.
