### ISSUE TITLE
Minigame reward too overpowered

### ISSUE THREAD

**Issue by Gorea235** [Nicodaw/Uni-UniversityDominationA4#20]
After some playtesting, I've found that the minigame reward is much too powerful. It can be found multiple times in a row by one player, and if they can play the minigame well, it can cause them to become much too powerful.

While this is partly down to the combat system not being properly balanced (see #5), it's also down to how the reward is calculated and distributed. I think we should tweat one or more of the following:

- Strength of the reward
- How often it spawns (i.e. only spawn after a given number of turns)
- Whether the old reward should be kept by the previous player

The last point is something we need to consider the most I think, as if only 1 player can have the reward, then it allows it to be more powerful while not disrupting gameplay.

**Comment by Nicodaw** [comment]
[I briefly said](https://github.com/Nicodaw/Uni-UniversityDominationA4/issues/17#issuecomment-374143090) that we can exchange the att/def bonus reward with a number of random cards as a first step to mitigating the inbalance. That doesn't solve the issue by itself, but that + introducing spawn times for the PVC is going to be enough. We might add the lastDiscoveredBy like last time, but I am not sure if it's really that much of an issue.

**Comment by Gorea235** [comment]
The spawn timer might be best to implement to stop multiple finds in succession, but I think the minigame reward being random cards is a good idea, and allows us to play with the reward much more.

**Comment by Gorea235** [comment]
I've added a spawn delay. It's set to 2 full cycles of player turns currently, allocating on the start of the player after the one who found it. This is configurable, but for now I think it will work well.

**Comment by Gorea235** [comment]
The minigame now rewards players with cards, 1-3 depending on score. The way it rewards players has been altered so that it now uses a lambda, meaning that it can be changed very easily in future.
