### ISSUE TITLE
Neutral player algorithm rework

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#4]
Current implementation
---------------------------
Just bizzare
Magically appearing units.
Magically disappearing units.
Conquering a sector with a neutral player's unit on it sometimes kills your unit, but conquers their sector ???

Desired functionality
----------------------
Ensure that the AI is moving consistently.
Possible issues causing bugs is a problem with neutral player executing his two turns simultaneously.

**Comment by Gorea235** [comment]
I have a more concrete idea on how the game will be now, so this bug should not be an issue after we rework how players are handled.

**Comment by Gorea235** [comment]
#7 should have fixed this. Not only is the entire codebase more stable, the AI now runs in a coroutine, meaning that there is a 0.5 second delay between moves (which should allow time for any problematic events to go through)
