### ISSUE TITLE
Dialog System rework

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#6]
Current implementation
---------------------------
After loading a game in which a player has been eliminated, the dialog for "eliminated player" will show when his turn comes.

Desired functionality
----------------------
Just don't do that lol.

**Comment by Gorea235** [comment]
oh lol i forgot about this. i'll close it for now, cause #7 should have solved this anyway. if it's still a problem, reopen it and i'll fix it
