### ISSUE TITLE
Update Unit tests and Testing plan

### ISSUE THREAD

**Issue by Nicodaw** [Nicodaw/Uni-UniversityDominationA4#9]
ET4.pdf deliverable requires to explain and justify any changes we make on the previous testing documentation. 
**Note:** previous team's documentations are inconsistent about test results, but a fact is that currently no unit tests pass.

**Comment by Gorea235** [comment]
As of 1f323dc, unit tests have been overhauled to work properly. Unfortunately, I haven't been able to get them all working, however this is due to the 'mangled' nature of the codebase as-is, meaning that further unit test improvement will have to be done after work on #7 is mostly underway.

**Comment by asyncmeonov** [comment]
Finalised alongside with #11
